### GET ALL
GET localhost:5000/api/v1/airports

### GET ALL COUNTRIES
GET localhost:5000/api/v1/countries

### CREATE NEW AIRPORT
POST localhost:5000/api/v1/airports
Content-Type: application/json

{
  "code" : "test_1",
  "name" : "AAAA",
  "country_id" : 14
}

### DELETE BY ID
DELETE localhost:5000/api/v1/airports/142